name: Main build

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'sha'
        required: false
        default: 'default'
        type: string
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      sha: 

    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: update sha
        if: ${{ github.event.inputs != null }}
        run: |
          echo "update sha"
          echo "GITHUB_SHA=${{ github.event.inputs.sha }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_SHA }}

      - name: debug
        run: |
          git rev-parse --short HEAD
