name: Main build

on:
  workflow_dispatch:
  push:
    branches:
      - main

inputs:
  sha:
    description: 'sha'
    default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: debug
        run: |
          echo "called"

      - uses: actions/checkout@v2
