name: Main build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: |
          echo "called"
          echo ${{ github.event }} | jq .

      - uses: actions/checkout@v2
