name: Main build

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'sha'
        required: false
        default: ''
        type: string
      env:
        description: 'デプロイする環境'
        default: test
        type: environment
      bool-condition:
        description: '真偽値'
        default: true
        type: boolean
      dep-sha:
        description: '依存リポジトリのsha'
        required: false
        default: ''
        type: string

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: update sha
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.sha != '' }}
        run: |
          pwd
          ls -l
          echo "update sha"
          echo "GITHUB_SHA=${{ github.event.inputs.sha }}" >> $GITHUB_ENV
          echo ${GITHUB_SHA::7}

      - name: debug1
        run: |
          pwd
          ls -l

      - uses: actions/checkout@v2
        with:
          ref: ${{ env.GITHUB_SHA }}

      - name: clone dependency repository
        run: |
          pwd
          ls -l
          cd ../
          git clone https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/kazamori/go-sql-executor.git
          ls -l
          cd go-sql-executor
          ls -l

      - name: debug2
        run: |
          pwd
          ls -l
          echo ${{ env.GITHUB_SHA }} | cut -c1-8
          git rev-parse --short HEAD
          git branch
          git log -n 1

      - name: debug3
        run: |
          pwd
          ls -l
